version: '3.5'

services:
  testdb:
    image: postgres:11
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      PGDATA: /data/postgres
    ports:
      - "5432:5432"

  check_testdb:
    image: foobic/pg_isready:latest
    environment:
      HOST: testdb
      RETRIES: 5
    command: /scripts/pg_isready.sh
